plugins {
    id 'com.android.application'
}

android {
    namespace 'com.skystream.ssmusicplayer'
    compileSdk 35

    defaultConfig {
        applicationId "com.skystream.ssmusicplayer"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "0.1.0"
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    testImplementation 'junit:junit:4.13.2'
}
